class LoremIpsum {
    constructor() {
        this.text = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In id congue ipsum. Sed luctus turpis vitae egestas dictum. Donec mollis accumsan ipsum ac molestie. Pellentesque quam felis, efficitur ut nunc vel, egestas pharetra arcu. Integer faucibus bibendum felis, eu bibendum mauris mollis a. Donec auctor, tortor eu placerat tempor, nisl metus luctus elit, sed tempor ligula enim quis odio. Donec quis viverra dui, vel fringilla eros. Vivamus tincidunt ac eros sit amet convallis.

        Morbi pellentesque sem sed semper rutrum. Proin accumsan turpis vel convallis consequat. Aliquam molestie est in ante aliquet, et viverra urna imperdiet. Nullam consequat consequat vulputate. Maecenas elit nunc, varius ac orci quis, laoreet rhoncus mauris. Sed ac mi nec erat accumsan fringilla. Nullam ultricies, urna sit amet malesuada mattis, ex magna sodales purus, sed sodales mi diam ac nisl. Duis vel commodo arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam convallis fringilla mattis. Mauris pellentesque, dolor nec sagittis sodales, nisl nisi ultrices justo, in malesuada libero odio a ligula. Pellentesque diam metus, semper eu augue a, venenatis malesuada turpis. Vivamus non molestie metus.
        
        Phasellus quis ipsum ut dolor blandit venenatis. Praesent non euismod nunc. Aliquam eu commodo nibh. Vivamus rhoncus risus at mauris luctus tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum vel erat fermentum, efficitur erat vitae, malesuada ligula. Ut cursus feugiat porttitor.
        
        Praesent hendrerit diam at arcu vehicula, sit amet vestibulum augue rutrum. Nullam maximus justo a placerat laoreet. Nullam malesuada lacus non felis tempus laoreet. Nullam ligula felis, interdum vitae orci quis, facilisis tempus ligula. Suspendisse at iaculis velit, sed maximus eros. Aenean vestibulum blandit tortor, vel varius felis feugiat sed. Quisque vel accumsan erat. Suspendisse convallis felis in massa ornare, quis interdum elit maximus. Sed eget mi non mi ultrices blandit nec at ex. Duis ultrices odio quis nisi semper, id dapibus augue posuere. Nunc ac lectus imperdiet, maximus mi finibus, pretium est. Nunc mattis vestibulum felis in elementum. Etiam id mi vitae tortor tempus mattis at eget tortor. Duis finibus hendrerit risus. Praesent vitae quam quis dolor aliquam vulputate eget et felis.
        
        Proin sit amet varius neque. Quisque sed auctor turpis. Integer sodales viverra augue, id hendrerit erat tincidunt et. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis eu semper sapien, in maximus tortor. Nam viverra lobortis sapien id faucibus. Vivamus viverra tincidunt sapien, at commodo dui laoreet id. Aenean ultrices nunc sit amet turpis mollis, id mattis dolor sodales. Etiam eleifend, ex id interdum rutrum, dolor erat volutpat quam, vitae lobortis metus risus a tortor. Fusce justo urna, hendrerit et felis nec, vulputate interdum augue. Integer leo est, vestibulum vitae faucibus quis, vehicula in dolor. Nunc congue viverra imperdiet.
        
        Nullam aliquam molestie justo vel placerat. Maecenas consectetur nibh enim, at viverra mi blandit eu. Suspendisse vulputate velit vitae risus varius, et molestie quam interdum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam sit amet posuere justo, at cursus leo. Nulla sed tincidunt lorem, sed rutrum ligula. Suspendisse potenti. Nunc imperdiet quam metus, eget auctor nunc feugiat sed. In hac habitasse platea dictumst. Integer et neque a velit luctus finibus. Quisque pellentesque massa gravida odio mattis, nec gravida ipsum luctus. Mauris dictum mollis bibendum. Duis sollicitudin metus in odio venenatis egestas.
        
        Morbi eu nisl eget elit finibus finibus. Phasellus eu hendrerit mi. Nullam non consectetur felis. Nullam tempus semper faucibus. In non justo orci. Donec eu eleifend turpis. Integer ante lorem, fermentum non leo semper, pellentesque posuere lorem. Integer quis maximus tortor. Phasellus sed ultricies metus. Nulla at eros et magna ultricies interdum. Morbi rutrum dolor facilisis, sodales dolor ac, sollicitudin turpis. Aliquam sit amet dictum ex. Pellentesque placerat euismod fermentum. Donec sed viverra orci, ut imperdiet augue. Curabitur leo ante, gravida vel metus sit amet, imperdiet semper nunc.
        
        Cras justo orci, tincidunt id tellus eget, lobortis egestas diam. Cras dapibus turpis id elit tincidunt, in luctus velit facilisis. Donec at augue eros. Quisque a dolor lacus. Ut blandit sem ante, tincidunt consectetur nisl egestas a. Morbi id sapien odio. Aenean consequat lobortis nisi at finibus. Donec eget facilisis velit, et venenatis ex. Vivamus sollicitudin felis scelerisque quam bibendum, non congue odio hendrerit. Quisque eu iaculis mi. Duis porttitor turpis ac lacus suscipit, vel consequat orci porttitor. Sed et sem bibendum turpis volutpat fermentum. Nam est neque, pretium non fringilla ut, finibus vitae dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
        
        Phasellus ante tortor, tincidunt et pulvinar a, vehicula in orci. Suspendisse mollis diam mauris, at cursus diam aliquam sit amet. Morbi consequat, diam eget placerat finibus, tellus massa sagittis lorem, quis congue ligula nibh quis nulla. Aenean eu lorem suscipit, rutrum turpis eu, sagittis magna. Etiam nec turpis a mi consequat rhoncus. Aenean pulvinar mi quis libero ornare sagittis non quis mi. Quisque dictum tellus a neque molestie, eget efficitur urna laoreet. Proin iaculis orci ex, a bibendum felis porttitor in. Nam mauris neque, pulvinar eu nibh non, tempor maximus libero. Vestibulum euismod dolor vel orci fermentum, vel gravida nisi viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse in mi hendrerit, iaculis libero vel, semper quam.
        
        Fusce metus nulla, laoreet eu congue at, tempus at dolor. Quisque rutrum urna et purus ultrices ornare. Morbi auctor tincidunt consectetur. Aenean vel tellus ut nisl iaculis aliquam. Maecenas suscipit bibendum ligula rhoncus vehicula. Suspendisse ut lectus sit amet lectus consectetur dictum. Phasellus tellus quam, pretium sed est non, malesuada fermentum diam. Mauris id neque vel dolor euismod euismod. Vestibulum dapibus at ligula sed pretium. Cras laoreet, urna et fermentum varius, nunc lacus ornare erat, consectetur vehicula turpis velit maximus orci. Fusce orci purus, fermentum vitae volutpat et, suscipit nec dolor. Nunc et varius ex.
        
        Curabitur ullamcorper convallis efficitur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ac ullamcorper nisl, ut lacinia mauris. Suspendisse at rhoncus elit. Pellentesque maximus lectus nec diam placerat, nec volutpat orci vehicula. Quisque lacinia dui id leo tincidunt sagittis. Etiam metus lacus, faucibus vel enim at, vulputate consectetur urna. Sed eget odio rutrum turpis pellentesque tincidunt eget ut dui. Aliquam erat volutpat. Nam fermentum purus risus, nec faucibus nunc consectetur eu. In imperdiet rutrum luctus. Proin vestibulum dui sed bibendum luctus. Quisque auctor blandit ante at sagittis. Maecenas tincidunt nisl aliquam tellus gravida facilisis. Nulla eleifend mattis sem nec posuere.
        
        Aenean auctor bibendum auctor. Morbi non eleifend metus, ut convallis nunc. Integer eu suscipit eros. Proin volutpat risus quis quam tincidunt, at iaculis sapien ultrices. Praesent facilisis dui ac maximus placerat. Quisque at nibh lacus. Curabitur quam arcu, condimentum ut finibus in, faucibus sagittis quam. Morbi semper at ante nec tincidunt. Nulla ultrices pulvinar vestibulum. Aenean sit amet cursus nisi. Nunc iaculis vestibulum mi, et luctus est suscipit et. Vestibulum nec elit porta, pellentesque sem eu, commodo neque. Fusce quis tempor velit.
        
        Integer tempor lobortis nunc nec molestie. Sed a dignissim libero, eu accumsan justo. Nulla rutrum ante nec dolor eleifend, id varius enim sodales. Vestibulum ac augue nec ligula sagittis tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum sit amet diam ut est viverra accumsan id eu est. Nullam efficitur, nulla at pulvinar consequat, orci purus bibendum nisi, tincidunt vulputate leo metus quis ipsum. Nam in placerat purus. Aliquam vitae tempus mi.
        
        Duis felis felis, lacinia vel enim eu, aliquet laoreet magna. Sed eu consectetur leo. Nunc auctor, ipsum scelerisque elementum sollicitudin, ex magna feugiat ligula, nec ullamcorper enim lorem vitae quam. Aliquam rhoncus pellentesque viverra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin malesuada a massa non pellentesque. Mauris nec dolor pretium, porttitor lacus ut, convallis libero. Aliquam rhoncus justo mi, sit amet aliquet arcu bibendum ut. Maecenas eget tellus vel tellus hendrerit feugiat. In et lacus ante. Fusce sit amet lorem rhoncus, suscipit nunc non, lacinia tortor. Nulla placerat risus ex, sed elementum nulla consectetur congue. Mauris at lacus vestibulum, aliquet risus eu, scelerisque erat.
        
        Proin in luctus tortor, ac gravida lorem. Cras vitae aliquam metus. Praesent sagittis libero vitae ante tincidunt malesuada. Aliquam at orci a est suscipit placerat. Ut ex dui, dapibus id justo eleifend, blandit commodo tortor. Nam vel enim condimentum nulla consequat placerat ut ac velit. Curabitur ut ex a lacus ornare imperdiet sed a lorem. Pellentesque at eros at ante maximus tempus quis sed nisl. Nunc ultrices sem id ipsum lobortis dictum. Curabitur nec lorem magna. Morbi viverra, libero eu pulvinar finibus, libero est imperdiet purus, non commodo augue tortor in urna. Maecenas vel orci at turpis bibendum condimentum. Sed a justo eu ligula placerat vulputate at at purus. Phasellus nec est ante.
        
        Cras malesuada, nisl non tincidunt cursus, neque ante auctor nisi, sed feugiat lorem sapien eu neque. Aliquam erat volutpat. Donec vehicula, justo id blandit pretium, tellus ante volutpat mauris, in rhoncus nisl odio quis diam. Cras sed condimentum tellus. Aliquam in nibh volutpat, auctor diam volutpat, lobortis ex. Aenean arcu sem, tempor a ex aliquet, sollicitudin mattis justo. Duis ut mauris interdum, lacinia risus eu, placerat turpis. Sed dui diam, dapibus at aliquet in, semper eget dui. Ut sapien sem, aliquet non nisi a, porttitor elementum libero.
        
        Mauris suscipit odio sem, quis laoreet lorem ornare ut. Sed quis arcu in ex pretium blandit. Curabitur luctus mauris justo, nec dapibus risus molestie sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin auctor sagittis bibendum. Praesent ut erat ligula. Maecenas viverra luctus ex, sit amet auctor quam eleifend eget. Aliquam aliquet condimentum laoreet. Donec accumsan molestie eleifend. Aliquam erat volutpat.
        
        In aliquam dictum dolor, vitae porta lacus cursus eget. Nam ultrices purus non dignissim facilisis. Donec eu tincidunt libero. Nunc blandit accumsan tempor. Vestibulum ut pharetra felis. Ut quam magna, fermentum sed varius ac, aliquam sed nisl. Pellentesque a mi elementum, consectetur velit vitae, iaculis nisi. Phasellus eu nisi ornare, porttitor erat vitae, placerat sem. Sed imperdiet ipsum turpis, nec maximus eros euismod nec. Nulla at augue quis urna vehicula interdum id in lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed euismod, nibh in convallis consectetur, nulla diam blandit mi, ut convallis nisl lectus vel risus. Praesent eget laoreet nisi. Cras vitae condimentum metus. Vivamus massa tortor, ultrices et rutrum sit amet, varius vitae tortor.
        
        Proin pretium finibus justo, faucibus tincidunt justo. Sed ut commodo enim. Nunc porta sem quis velit tempus, eget aliquam justo maximus. Praesent volutpat dictum libero in hendrerit. Ut ac enim ante. Duis blandit viverra nisi, ut lacinia odio porttitor nec. In augue mauris, dignissim sed dui semper, accumsan cursus metus. Vestibulum fermentum ultricies sem vel porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed nec sodales velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique dictum sodales. Fusce mauris arcu, consectetur id enim non, tincidunt rutrum mi. Morbi sit amet dolor cursus odio varius lacinia. Proin volutpat mi eget lobortis varius. Sed eget ligula metus.
        
        Pellentesque consectetur cursus quam vitae maximus. Ut at convallis lectus. Praesent venenatis varius massa in pellentesque. Donec at dolor varius, interdum diam et, laoreet neque. Nunc et congue enim. Vivamus dignissim faucibus magna nec consectetur. Duis bibendum nunc a lacus fringilla, ac malesuada libero tempor. Vestibulum sit amet massa sagittis, fermentum ligula at, rhoncus nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam at tellus ut mi dignissim maximus. Donec elementum, enim nec aliquet congue, ipsum massa cursus risus, eget congue velit eros nec justo. Donec sit amet ligula ut massa vehicula hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        
        Sed auctor sit amet velit a viverra. Quisque tincidunt in diam et pharetra. Aliquam sodales et nibh sed euismod. Maecenas eu massa est. Ut rutrum imperdiet nunc, at hendrerit lectus bibendum quis. Proin non felis eget libero laoreet tempor at sit amet nisi. Integer dictum quam pretium, pulvinar nisi nec, rutrum augue. Morbi id dolor in sem euismod blandit. Nunc interdum metus ut metus pellentesque aliquam. Proin tincidunt pulvinar fringilla.
        
        Vivamus eget tincidunt tellus. In a velit id turpis rhoncus facilisis a eget eros. Quisque condimentum lacinia posuere. Ut eget leo tincidunt, tincidunt orci ut, sagittis urna. Donec lorem ipsum, faucibus eu sem ac, suscipit ultricies dolor. Phasellus augue turpis, mattis vel mi nec, interdum sollicitudin lorem. Praesent quis odio lorem. Donec eget libero quis lectus luctus sodales.
        
        Ut consectetur lacus et commodo viverra. Aenean mollis gravida imperdiet. Morbi mollis ultrices odio, ut molestie arcu fringilla non. Quisque id lectus leo. Pellentesque urna odio, faucibus in magna ac, imperdiet fringilla mi. Vestibulum vitae eros eu lectus imperdiet pulvinar vel nec mi. Ut varius in velit nec mollis.
        
        Donec ullamcorper luctus ante, accumsan rutrum tortor pharetra ut. Maecenas sed elit laoreet, lacinia arcu sit amet, venenatis purus. Sed ultricies semper purus, a finibus nibh consequat et. Mauris molestie velit at turpis dignissim, a consequat purus faucibus. Mauris interdum a eros eget dignissim. Etiam malesuada facilisis enim, et sagittis nibh porttitor at. Nam id hendrerit tellus, in molestie enim. Ut congue, urna ut gravida consectetur, ante velit blandit velit, sit amet posuere velit massa ut erat. Mauris cursus nunc tellus, eu congue nisi blandit vitae. Phasellus dignissim sapien sit amet tempor euismod. Quisque at varius augue. Nam congue condimentum metus, ac blandit ante rutrum laoreet. Nulla et tristique eros. Ut id magna mattis, suscipit ligula nec, interdum odio.
        
        In quam orci, sodales non est non, venenatis fermentum orci. Etiam sit amet dui in metus vestibulum maximus. Proin ullamcorper magna nec aliquet porta. Aenean pulvinar vitae tortor et tincidunt. Proin volutpat purus eros, in feugiat libero rhoncus quis. Ut rutrum sodales pellentesque. Vestibulum vel purus turpis. Donec eu mattis mauris. Vivamus egestas efficitur turpis, at ultrices leo pulvinar nec.
        
        Sed vel lorem blandit sem elementum tempor et sed elit. Aliquam erat volutpat. Nunc enim nunc, finibus in tempus sed, elementum eget enim. Etiam rutrum eros massa, in lobortis mi iaculis a. In vel dolor quis est dictum vulputate. Maecenas pharetra sodales urna et vehicula. Integer mollis nisl in lectus ultricies porttitor. Quisque non elit ante. Nullam pretium lobortis massa, ac eleifend elit vehicula ut. Curabitur sed mauris at nisl euismod semper. Maecenas ac sem at sem accumsan tincidunt id in elit. Maecenas in justo efficitur, tempor massa eu, maximus nibh. Curabitur tortor erat, efficitur vel malesuada ut, pretium eu urna.
        
        In dictum ultrices nunc ac fermentum. Etiam imperdiet condimentum lorem sit amet cursus. Proin in augue molestie, rhoncus erat pulvinar, posuere metus. Praesent consectetur consectetur lobortis. Pellentesque sit amet massa a velit dictum ultrices. Pellentesque congue, odio id fermentum convallis, justo turpis dictum ex, non malesuada enim velit id justo. Vestibulum fringilla elementum fringilla. Aenean et pharetra eros, et sagittis turpis. Nulla auctor egestas molestie. Cras vitae egestas nulla. Ut sodales at velit non sagittis. Nullam sit amet semper mauris, laoreet ullamcorper elit. Curabitur non magna sed velit malesuada interdum eget eget ante. Nullam eget ex scelerisque, ultricies eros ac, ullamcorper mauris.
        
        Phasellus porta sagittis sapien, in lacinia lacus. Ut id cursus neque. Donec quis maximus quam, ac fermentum velit. Phasellus finibus finibus vulputate. Cras id varius dolor. Fusce sed neque ut dolor gravida pharetra. Maecenas gravida ultrices eleifend. Nulla mollis sem eget arcu pretium, at ornare metus suscipit. Aliquam erat volutpat. Pellentesque non sodales nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse fermentum laoreet diam, sit amet maximus est ultricies suscipit. Duis venenatis iaculis quam. Mauris in finibus ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent a libero iaculis, tristique turpis sed, vulputate nibh.
        
        Quisque aliquet, eros ut tempor malesuada, urna ipsum mollis quam, mattis dignissim mauris est at ligula. Curabitur dapibus diam nulla, vel varius neque feugiat eget. Nulla scelerisque lobortis purus. Aenean nunc erat, sodales id pharetra ac, varius lobortis urna. Nam tincidunt tempor quam id dignissim. Fusce ut metus velit. Quisque dignissim massa ut est luctus, et vehicula felis placerat. Proin in arcu nec arcu aliquet vehicula ac in ligula. Donec eget ligula vel metus aliquet dictum.
        
        Suspendisse consequat nibh dui. Phasellus tempus ante sed felis aliquet consectetur. Curabitur vitae lacus ut mi commodo dapibus. Aliquam consequat arcu eget libero venenatis, non feugiat dolor scelerisque. Aenean at magna semper purus laoreet facilisis. Curabitur eros urna, dictum eget luctus in, faucibus id est. Duis interdum orci eget cursus interdum.
        
        Donec elementum, sem non porta varius, sapien nulla tincidunt ex, nec sollicitudin nisl orci at purus. Quisque pulvinar dapibus libero eu ullamcorper. Vivamus aliquet ante est, tempor ultrices erat cursus tempus. Nunc aliquam feugiat auctor. Integer id nunc sed lorem consectetur egestas. Curabitur a nibh efficitur, facilisis augue eget, tincidunt lectus. Etiam condimentum elit est, et scelerisque dolor vehicula at.
        
        Etiam quis leo in ante luctus gravida a ut nibh. In facilisis dictum metus eget laoreet. Morbi rhoncus neque sodales lectus ultrices, non vulputate felis fermentum. Vestibulum ipsum nulla, viverra in felis ut, maximus gravida nisi. Aliquam molestie mauris ac lectus faucibus, quis elementum urna sagittis. Pellentesque ut blandit felis, pulvinar finibus nisl. Fusce in augue id eros mattis pellentesque.
        
        Vestibulum pretium nulla et odio lacinia, ac fringilla tellus porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam erat volutpat. Curabitur tempor tortor quis lacus commodo, a bibendum nibh hendrerit. In interdum commodo sem non porta. Sed faucibus justo sed magna gravida mollis. Donec molestie non velit rhoncus malesuada. Curabitur blandit justo facilisis ante facilisis, efficitur porta elit condimentum. Pellentesque ac sapien eget risus posuere dignissim. Sed a enim id arcu ullamcorper placerat condimentum a arcu.
        
        Maecenas aliquet enim sapien, ac malesuada urna dignissim sed. Fusce eget nulla vitae magna laoreet congue sit amet et lectus. Aenean sodales ac metus quis sollicitudin. Nulla bibendum tellus vel arcu finibus laoreet. Phasellus mollis porttitor congue. Mauris eu congue lectus, vitae tempus justo. Aenean efficitur tincidunt risus eu consequat. Nullam non consectetur dolor, id accumsan justo. Mauris sagittis risus velit, quis molestie lacus consequat at. Cras non mi ac nulla porta lacinia. Nam consequat neque non sapien consectetur, sed hendrerit quam maximus. Fusce ut mollis nisl. Integer semper risus ac dolor condimentum laoreet. Praesent condimentum varius purus eget convallis. Aliquam erat volutpat.
        
        Aliquam viverra augue in tellus pretium pulvinar. Morbi at orci fringilla, interdum risus sed, dictum dui. Aliquam id dolor lorem. Morbi lectus ligula, facilisis ac elit vitae, scelerisque aliquam tortor. Ut nulla lectus, mollis vel gravida porta, mollis at ligula. Nulla placerat laoreet ex nec placerat. Donec eget tortor odio. Maecenas risus nulla, suscipit vel efficitur sit amet, bibendum sollicitudin eros. Proin fermentum scelerisque odio. Pellentesque volutpat nulla tellus, quis posuere massa congue id. Maecenas in nisi ex. Mauris viverra auctor nisl in commodo. In purus tortor, faucibus id fringilla eget, euismod at leo. Cras ac mollis mi.
        
        Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris vestibulum sodales commodo. In mattis blandit massa, auctor ultricies tellus viverra sed. Cras urna augue, lacinia ac erat vel, facilisis vehicula quam. Cras dolor lorem, hendrerit vel lorem non, cursus bibendum sem. Morbi tempor risus eu arcu tristique laoreet. Vivamus maximus, quam ut volutpat cursus, dolor ipsum hendrerit massa, ac eleifend mi est ut velit. In at ipsum eu arcu commodo blandit. Nunc et vestibulum orci.
        
        Nulla eget enim nisi. Aenean pulvinar viverra arcu nec rutrum. Morbi ultrices, est et fringilla ullamcorper, massa dolor semper nisi, id vehicula mi orci id mauris. Integer rhoncus vehicula elit, vitae vestibulum arcu lacinia ac. Phasellus a condimentum neque. Nullam nec leo id enim ultrices porta. Nam suscipit leo a augue imperdiet, finibus dignissim odio laoreet. Pellentesque vitae malesuada dolor, id sollicitudin magna. Quisque faucibus pulvinar mi, nec placerat justo consectetur vitae. Quisque dignissim tincidunt mattis. Sed tempor vehicula condimentum. Quisque eget convallis odio. Suspendisse in justo semper, auctor est vel, porttitor neque.
        
        Cras fermentum ullamcorper purus aliquam volutpat. Donec dui lectus, congue ut sem ac, commodo pellentesque dui. Maecenas vestibulum, ligula eu vehicula varius, sem metus euismod lectus, sit amet convallis arcu est id ipsum. In feugiat dui quam, eget pulvinar neque consectetur quis. Nullam ac congue erat. Sed vitae condimentum urna, eget consectetur ipsum. Duis commodo dolor orci, molestie auctor ante vestibulum quis. Aliquam vel erat ac nibh euismod aliquam. Pellentesque nec laoreet libero. Integer eu mattis ex. Suspendisse dictum nec turpis nec venenatis.
        
        Vivamus lorem ante, vehicula ut arcu quis, hendrerit elementum ex. Vestibulum bibendum dolor aliquet dignissim ornare. Curabitur mollis mi enim, non convallis metus pretium eu. Nunc venenatis elit vitae nibh consectetur bibendum. Vestibulum ex mauris, viverra a efficitur sagittis, hendrerit id sapien. Nam nec sem facilisis, gravida elit et, iaculis urna. Praesent feugiat interdum dictum. Curabitur placerat ac dolor nec viverra. Etiam commodo volutpat sem, ac mollis diam interdum et. Nunc eget sagittis ex. In consequat, ligula eu mattis aliquet, libero dui porta est, in viverra nisi est vitae justo. Sed eu ultricies sapien, ac congue ante. In at suscipit felis. Etiam eu felis a diam fringilla faucibus vitae eget dolor.
        
        Duis et velit non tortor finibus finibus. Suspendisse nunc magna, interdum vitae diam ac, fringilla bibendum odio. Ut laoreet consectetur est. Nam imperdiet lorem porta turpis consectetur, in ornare neque placerat. Nam tempus blandit magna at vulputate. Nunc mollis ut enim lobortis eleifend. Duis consectetur nec odio tempor pharetra. Integer a fermentum nunc, et accumsan lorem. In hac habitasse platea dictumst. Cras vitae lacinia lacus, sed mattis dolor. Morbi pulvinar risus sed quam aliquam, at commodo diam vestibulum. Sed bibendum lacus orci, nec aliquam urna volutpat ut.
        
        Praesent commodo dui felis, eget iaculis eros blandit vel. Pellentesque egestas tellus nibh, in elementum metus iaculis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse vulputate maximus aliquet. Sed non nisi ac neque varius bibendum. Sed elit nunc, lacinia commodo quam pharetra, ultricies mattis massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque non dignissim nisi, sed pulvinar enim. Quisque a tincidunt felis. Mauris scelerisque ex laoreet lacinia hendrerit. Donec sit amet lectus ac ipsum vulputate volutpat vitae vel massa. In scelerisque orci non augue gravida molestie. Nullam fringilla, dui nec mollis tincidunt, orci quam euismod magna, id pharetra nulla eros sed nisi. Nam ex odio, eleifend sit amet ligula gravida, bibendum ullamcorper dui. Suspendisse tempus libero efficitur aliquam vehicula.
        
        Nulla facilisi. Nulla mi tellus, ornare ac erat vel, commodo imperdiet nisi. In tristique dignissim nisi, et semper lorem tincidunt sit amet. Quisque quis sem nibh. Aliquam erat volutpat. Phasellus risus diam, rhoncus eu congue vel, aliquet eget dui. Maecenas laoreet tincidunt mi posuere molestie. Proin in enim tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dignissim lectus et pellentesque fermentum. Mauris at lacus tortor. Morbi eu pharetra justo, in laoreet felis.
        
        Nullam nec odio sollicitudin, tempor quam sit amet, tempor mauris. Integer rhoncus et lorem sit amet tincidunt. Suspendisse quis lacus urna. Sed in massa sed ligula tincidunt placerat scelerisque et nibh. Curabitur hendrerit lectus in nulla blandit dignissim. In vel ex quis turpis mollis condimentum vel et dolor. Nullam felis urna, imperdiet ut nisi vitae, efficitur commodo arcu. In hac habitasse platea dictumst. Duis et ipsum non felis aliquet vehicula. Proin quis varius nunc. Cras rutrum dignissim orci sed iaculis. Etiam non feugiat felis.
        
        Nam varius odio eget erat fermentum, vitae rhoncus lorem vestibulum. Integer tincidunt sem et eleifend pellentesque. Duis consequat sem eu ante sodales, sit amet tristique sem accumsan. Curabitur rhoncus purus quis ligula euismod, at suscipit ipsum suscipit. Vestibulum sed elit ac odio varius sollicitudin at vitae tellus. Vivamus porta bibendum dictum. Praesent at mi vel lorem faucibus dignissim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras mauris risus, accumsan nec laoreet quis, tristique a nulla. Morbi vulputate massa vel orci cursus auctor. Fusce id lacinia ipsum, sit amet dapibus tortor. In volutpat vitae felis at aliquam. Donec sit amet urna purus. Aenean feugiat aliquet libero, ut ultrices libero venenatis id. Proin scelerisque libero vitae ultricies sagittis. Curabitur non tortor nec dui vestibulum gravida.
        
        Quisque vel urna erat. Donec dui turpis, pharetra ac quam vel, tempus fermentum massa. Integer pellentesque nisl massa, eu consequat enim tempor vitae. Suspendisse ultricies et diam euismod pellentesque. Phasellus ultrices tristique felis sed tristique. Nulla sed metus in leo sagittis consectetur. Donec gravida sapien at ante pharetra, sed volutpat neque imperdiet. Integer nisi magna, mattis et tincidunt sit amet, elementum ut lorem. Mauris mollis erat interdum, cursus neque sed, lacinia ipsum. Praesent sed dolor elit. Praesent non quam sed libero pellentesque aliquet sed a felis. Phasellus tincidunt, nunc placerat euismod laoreet, nibh sapien placerat enim, nec ullamcorper dui justo vitae orci. Vivamus ut consectetur odio, sit amet vestibulum velit. Proin hendrerit mollis lacus, sed varius nibh lobortis non. Maecenas ex purus, maximus hendrerit odio sit amet, mollis pellentesque dolor.
        
        Donec eleifend ante at ante dignissim, non vestibulum diam pulvinar. Nullam congue luctus metus, in tempor sapien imperdiet sed. Vivamus ligula nisl, tincidunt quis orci ac, maximus elementum nisl. Suspendisse maximus congue turpis vel lacinia. Morbi ullamcorper lorem ornare scelerisque cursus. Proin rhoncus hendrerit orci, sit amet vehicula lacus feugiat a. Nulla in lorem eros. Nullam pellentesque massa id arcu porttitor hendrerit. Vivamus blandit massa in odio fermentum, sit amet varius tortor pharetra.
        
        Sed interdum, sem eget pretium dapibus, elit lorem euismod mi, blandit suscipit enim justo sed lectus. Vestibulum augue leo, suscipit vel mauris et, euismod facilisis turpis. Curabitur turpis est, ullamcorper eu varius vitae, malesuada sed ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla facilisi. Morbi quis ligula ornare, pellentesque lectus ut, vestibulum purus. Donec sem tellus, luctus id cursus vitae, convallis sed nibh.
        
        Vivamus fringilla eros eu orci elementum, ultrices sagittis est placerat. Curabitur aliquam porttitor viverra. Quisque feugiat molestie sapien. Vestibulum tincidunt, sem fermentum vulputate feugiat, purus purus facilisis nisi, a pretium massa libero vitae nisl. Suspendisse at nibh ante. Pellentesque nec tincidunt urna. Donec sagittis dui quis nisi lobortis, nec rutrum risus efficitur. Curabitur a leo at magna condimentum hendrerit quis nec felis. Sed pulvinar ligula vel turpis imperdiet, ut pulvinar mi accumsan. Duis interdum sagittis finibus.
        
        Donec porta ullamcorper iaculis. Vestibulum mollis velit at libero sollicitudin dapibus. Integer ultricies, tellus sed viverra feugiat, leo justo dapibus massa, quis cursus elit dui quis leo. Quisque luctus vitae lectus eget tristique. Proin ornare ante eget tellus consectetur vestibulum. Duis venenatis enim massa, non fermentum purus fringilla a. Aliquam dignissim ipsum vulputate justo tempor sagittis. Morbi placerat velit ac semper dapibus. Morbi et commodo magna. Nam a eros quis turpis dictum ultricies. Quisque vel facilisis libero.
        
        Fusce vel pellentesque massa. Nam viverra libero arcu, eget aliquet leo ultricies id. Phasellus malesuada egestas congue. Donec orci arcu, interdum sed felis at, maximus egestas nisl. Praesent sed leo vitae libero facilisis varius a ut nisl. Etiam euismod aliquet euismod. Integer fermentum nisi nec nisi consectetur, eu fringilla purus congue. Integer viverra orci quis aliquet dapibus. Sed vel erat euismod mauris condimentum blandit ac a lectus. Aenean est sem, semper sed mollis in, iaculis egestas justo. Maecenas bibendum enim at augue ullamcorper, quis euismod mi fermentum. Maecenas in arcu nulla. Vivamus lacinia felis non quam ornare, ac ultrices diam tincidunt.
        
        Fusce eget magna ac nulla accumsan fermentum. Donec condimentum pharetra elementum. Sed et sapien ut orci interdum tincidunt non sed dui. Aenean quis ante euismod, sodales ipsum ut, rutrum est. In hac habitasse platea dictumst. Integer vel convallis metus. Nam vel tristique dolor, ac gravida sapien. Mauris vel risus leo. Proin ligula magna, venenatis luctus mi quis, pharetra consequat nibh. Donec rhoncus, urna sed mollis vehicula, risus velit egestas augue, a dapibus tellus ipsum vel erat. Fusce nec ex vehicula, molestie mi aliquam, facilisis dolor. Nunc et fringilla nisi.
        
        Nam eu ultricies lorem. Sed egestas laoreet mauris. Donec quis justo vel erat interdum ultricies. Duis bibendum imperdiet quam, fermentum vehicula nisi gravida non. Morbi eleifend faucibus lorem, vel lacinia sem vestibulum in. Vestibulum volutpat porttitor est, nec facilisis erat egestas eget. Praesent neque velit, lobortis in bibendum id, scelerisque at nunc. Aliquam placerat, risus eget finibus tristique, sapien diam venenatis libero, ac placerat leo ipsum non nulla. Ut et interdum tortor. Etiam pellentesque aliquam erat sit amet tincidunt.
        
        Sed ut justo id magna ullamcorper bibendum. Nulla hendrerit finibus orci, et malesuada tellus congue in. Suspendisse potenti. Morbi eu sem non diam pharetra posuere. Pellentesque non hendrerit ligula, sed auctor magna. Donec tincidunt fermentum nibh sit amet laoreet. Curabitur a ornare tortor. Nulla facilisi. Phasellus dignissim dolor est, et fringilla est maximus a. Phasellus eget lacus eu erat porta posuere. Aenean lobortis in sapien nec rhoncus. Aenean dui odio, elementum nec velit vel, gravida lobortis odio. Aenean id urna ut neque dapibus rutrum. Donec fermentum ligula consectetur purus ultrices vestibulum. Sed viverra ex sed orci tincidunt, eget fermentum risus lacinia.
        
        Suspendisse eu ultrices nibh. Cras volutpat tortor at libero pharetra, vel consequat mi sodales. Donec dapibus, diam non placerat efficitur, diam odio finibus tellus, vitae gravida dolor erat id odio. Sed sollicitudin sollicitudin nulla eu luctus. Vivamus vitae placerat orci. Morbi nec tempus nulla. Nunc laoreet luctus libero ac varius. Maecenas ut arcu in nulla imperdiet pharetra.
        
        Donec consequat, nulla quis facilisis fringilla, erat felis tempus arcu, at egestas nunc arcu volutpat eros. Sed massa sapien, ullamcorper eget diam quis, molestie scelerisque tortor. Donec fringilla pulvinar ex sed ullamcorper. Proin at egestas felis. Sed quis ligula augue. In quis lacinia quam. Duis sodales gravida lacus, eu suscipit dui sagittis vitae. Nam hendrerit eros in nibh condimentum laoreet. Aliquam nec risus cursus, facilisis est sit amet, elementum sapien.
        
        Quisque sit amet metus pellentesque, consequat nibh vitae, accumsan elit. Donec luctus nulla non neque lacinia ornare. Proin viverra nisl eros, non condimentum ante fringilla vitae. Proin eget ligula sit amet nulla facilisis blandit nec sed augue. Suspendisse vitae viverra lacus. Sed interdum pulvinar bibendum. Curabitur vitae imperdiet mi. In vestibulum purus ac velit sollicitudin, vel vehicula nibh maximus.`;
        this.json = {
            "a": this.text,
            "b": this.text + this.text
        };
        this.textSmall = "uet consectetur. Curabitur vitae lacus ut mi commodo dapibus. Aliquam consequat arcu eget libero venenatis, non feugiat dolor scelerisque. Aenean at magna semper purus laoreet facilisis. Curabitur eros";
        this.textMedium = `rhoncus facilisis a eget eros. Quisque condimentum lacinia posuere. Ut eget leo tincidunt, tincidunt orci ut, sagittis urna. Donec lorem ipsum, faucibus eu sem ac, suscipit ultricies dolor. Phasellus augue turpis, mattis vel mi nec, interdum sollicitudin lorem. Praesent quis odio lorem. Donec eget libero quis lectus luctus sodales.
        
        Ut consectetur lacus et commodo viverra. Aenean mollis gravida imperdiet. Morbi mollis ultrices odio, ut molestie arcu fringilla non. Quisque id lectus leo. Pellentesque urna odio, faucibus in magna ac, imperdiet fringilla mi. Vestibulum vitae eros eu lectus imperdiet pulvinar vel nec mi. Ut varius in velit nec mollis.
        
        Donec ullamcorper luctus ante, accumsan rutrum tortor pharetra ut. Maecenas sed elit laoreet, lacinia arcu sit amet, venenatis purus. Sed ultricies semper purus, a finibus nibh consequat et. Mauris molestie velit at turpis dignissim, a consequat purus faucibus. Mauris interdum a eros eget dignissim. Etiam malesuada facilisis enim, et sagittis nibh porttitor at. Nam id hendrerit tellus, in molestie enim. Ut congue, urna ut gravida consectetur, ante velit blandit velit, sit amet posuere velit massa ut erat. Mauris cursus nunc tellus, eu congue nisi blandit vitae. Phasellus dignissim sapien sit amet tempor euismod. Quisque at varius augue. Nam congue condimentum metus, ac blandit ante rutrum laoreet. Nulla et tristique eros. Ut id magna mattis, suscipit ligula nec, interdum odio.
        
        In quam orci, sodales non est non, venenatis fermentum orci. Etiam sit amet dui in metus vestibulum maximus. Proin ullamcorper magna nec aliquet porta. Aenean pulvinar vitae tortor et tincidunt. Proin volutpat purus eros, in feugiat libero rhoncus quis. Ut rutrum sodales pellentesque. Vestibulum vel purus turpis. Donec eu mattis mauris. Vivamus egestas efficitur turpis, at ultrices leo pulvinar nec.
        
        Sed vel lorem blandit sem elementum tempor et sed elit. Aliquam erat volutpat. Nunc enim nunc, finibus in tempus sed, elementum eget enim. Etiam rutrum eros massa, in lobortis mi iaculis a. In vel dolor quis est dictum vulputate. Maecenas pharetra sodales urna et vehicula. Integer mollis nisl in lectus ultricies porttitor. Quisque non elit ante. Nullam pretium lobortis massa, ac eleifend elit vehicula ut. Curabitur sed mauris at nisl euismod semper. Maecenas ac sem at sem accumsan tincidunt id in elit. Maecenas in justo efficitur, tempor massa eu, maximus nibh. Curabitur tortor erat, efficitur vel malesuada ut, pretium eu urna.
        
        In dictum ultrices nunc ac fermentum. Etiam imperdiet condimentum lorem sit amet cursus. Proin in augue molestie, rhoncus erat pulvinar, posuere metus. Praesent consectetur consectetur lobortis. Pellentesque sit amet massa a velit dictum ultrices. Pellentesque congue, odio id fermentum convallis, justo turpis dictum ex, non malesuada enim velit id justo. Vestibulum fringilla elementum fringilla. Aenean et pharetra eros, et sagittis turpis. Nulla auctor egestas molestie. Cras vitae egestas nulla. Ut sodales at velit non sagittis. Nullam sit amet semper mauris, laoreet ullamcorper elit. Curabitur non magna sed velit malesuada interdum eget eget ante. Nullam eget ex scelerisque, ultricies eros ac, ullamcorper mauris.
        
        Phasellus porta sagittis sapien, in lacinia lacus. Ut id cursus neque. Donec quis maximus`;
        this.jsonSmall = {
            "a": this.textSmall,
            "b": this.textSmall + this.textSmall
        };
    }
}